version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: quibbler_db
    restart: always
    volumes:
      - ./sql/mysql-files:/var/lib/mysql-files:rw
      - ./sql:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_DATABASE: ps_quibbler
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3308:3306"