server:
  port: 8080
  servlet:
    application-display-name: quibbler

spring:
  datasource:
    url: jdbc:mysql://xxx/quibbler?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_
  mapper-locations: classpath*:/mapper/**Mapper.xml


jwt:
  header: Authorization
  expire: 604800
  secret: xxx
  prefix: Bearer
