server:
  port: 8089
  servlet:
    application-display-name: quibbler

spring:
  datasource:
    url: jdbc:mysql://xxx/quibbler?serverTimezone=GMT&useUnicode=true&characterEncoding=utf8
    username: xxx
    password: xxx
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    jedis:
      pool:
        min-idle: 5
        max-active: 10
        max-idle: 10
        max-wait: 2000
    database: 0
    host: xxx
    port: 6379
    password: xxx
    timeout: 1000
  cache:
    type: redis
    cache-names: redisCache
  rabbitmq:
    host: xxx
    port: 5672
    username: xxx
    password: xxx
    virtual-host: /
    #手动确认消息
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 3
    # MQ消息确认机制
    publisher-confirm-type: correlated
    # 打开消息返回
    publisher-returns: true
    template:
      mandatory: true
  elasticsearch:
    rest:
      uris:
      username:
      password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: t_
  mapper-locations: classpath*:/mapper/**Mapper.xml


jwt:
  header: Authorization
  expire: 604800
  secret: xxx
  prefix: Bearer

